#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey '^[[1;9C' forward-word
bindkey '^[[1;9D' backward-word

alias ga='git add'
alias gst='git status'
alias fs='foreman s -p 3000'
alias bfg='java -jar bfg.jar'
alias subl='//Applications/"Sublime Text.app"/Contents/SharedSupport/bin/subl'
alias dk='docker'
alias dkk='docker kill'
alias dkka='docker kill $(dk ps -aq)'
alias dkrma='docker rm $(docker ps -aq)'
alias dkc='docker-compose'
alias dkcu='docker-compose up'
alias dkck='docker-compose kill'
alias dkcr='docker-compose rm'
alias pcat='pygmentize -g -O style=colorful,linenos=1'
alias artisan='php artisan'
alias findyou='lsof -n -i | grep LISTEN'
alias liamneeson='function __liamneeson() {
                kill $(findyou | grep $1 | awk '\''{print $2}'\'' )
               }; __liamneeson'

### Third Part Sourcing


# DirEnv Init
# eval "$(direnv hook zsh)"
#
# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
#
# # Source Pyenv
# if command -v pyenv 1>/dev/null 2>&1; then
#   eval "$(pyenv init -)"
# fi
#
# # Source NVM
# export NVM_DIR=~/.nvm # Add NVM to PATH for scripting
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
#
# # place this after nvm initialization!
# autoload -U add-zsh-hook
# load-nvmrc() {
#   if [[ -f .nvmrc && -r .nvmrc ]]; then
#     nvm use
#   fi
# }
# add-zsh-hook chpwd load-nvmrc
# load-nvmrc
#
# [[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc
# export PATH="$PATH:/usr/local/opt/openssl/bin"
# export PATH="$PATH:$HOME/.composer/vendor/bin"
# export ANDROID_HOME=$HOME/Library/Android/sdk
# export PATH=$PATH:$ANDROID_HOME/tools
# export PATH=$PATH:$ANDROID_HOME/tools/bin
# export PATH=$PATH:$ANDROID_HOME/platform-tools
# export PATH="$(yarn global bin):$PATH"

### Added by the Heroku Toolbelt
# export PATH="$PATH:/usr/local/heroku/bin"
